---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: cadastro-projetos
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: cadastro-projetos
    tier: frontend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: cadastro-projetos
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: cadastro-projetos
    tier: database
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: cadastro-projetos
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cadastro-projetos
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cadastro-projetos
        tier: frontend
    spec:
      containers:
        - name: app
          image: cadastro-projetos:latest
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - "sleep 15 && npx sequelize-cli db:migrate && (npx sequelize-cli db:seed:all || true) && npm start"
          env:
            - name: DB_NAME
              value: cadastro_produtos
            - name: DB_HOST
              value: db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Developer@3306
            - name: SECRET_KEY
              value: F}R%`5UlK_u8~O}S9xF(1li1Dw(Vf{sSy*SVu`q,HJ1?%PH#<EQtfbxm4AaiPB>
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
            - name: SESSION_EXPIRY
              value: "8640000"
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: node-modules
          emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: cadastro-projetos
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadastro-projetos
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cadastro-projetos
        tier: database
    spec:
      containers:
        - name: db
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Developer@3306
            - name: MYSQL_DATABASE
              value: cadastro_produtos
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}